apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x2u3slg14-go-gitops
  description: This is GitOps manifest for x2u3slg14-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: x2u3slg14-go
    janus-idp.io/tekton: x2u3slg14-go 
    backstage.io/kubernetes-id: x2u3slg14-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x2u3slg14-go
